#!/usr/bin/env python3
import hashlib
import getpass
from pathlib import Path

CONFIG_FILE = Path("password_config.js")

def main():
    print("=== Lab 3 Password Update Tool ===")
    
    # Prompt without echo
    pwd = getpass.getpass("Enter new password: ")
    pwd2 = getpass.getpass("Re-enter new password: ")

    if pwd != pwd2:
        print("Error: passwords do not match.")
        return

    # Compute SHA-256 hash (hex)
    h = hashlib.sha256(pwd.encode("utf-8")).hexdigest()
    print(f"New SHA-256 hash: {h}")

    content = f"""// Auto-generated password configuration.
// Do NOT edit this file manually; use update_password.py instead.

const PASSWORD_HASH = "{h}";
"""

    CONFIG_FILE.write_text(content, encoding="utf-8")
    print(f"Wrote new password hash to {CONFIG_FILE.name}")

if __name__ == "__main__":
    main()
